// Package go_provider is an autogenerated binder stub for package provider.
//   gobind -lang=go code.google.com/p/mppq/examples/libprovider/provider
//
// File is generated by gobind. Do not edit.
package go_provider

import (
	"code.google.com/p/mppq/examples/libprovider/provider"
	"golang.org/x/mobile/bind/seq"
)

func proxy_Start(out, in *seq.Buffer) {
	param_serviceName := in.ReadUTF16()
	provider.Start(param_serviceName)
}

func init() {
	seq.Register("provider", 1, proxy_Start)
}
